In [99]:
dataset = [
    "I woke up early and made myself a cup of coffee",
    "The sun was shining through the curtains this morning",
    "I took a short walk before starting my work",
    "My phone buzzed with a message from an old friend",
    "Breakfast tasted better than usual today",
    "I watered the plants and watched the leaves shimmer in the light",
    "There was a gentle breeze outside my window",
    "I turned on some music to make the morning feel lighter",
    "The cat jumped on the table looking for attention",
    "I checked my emails before the day got too busy",
    "Lunch was simple but surprisingly delicious",
    "I tried a new recipe I found online last night",
    "After lunch I sat down with a cup of tea and a book",
    "The story pulled me in until I lost track of time",
    "I went out to buy groceries and bumped into a neighbor",
    "The supermarket was quieter than usual today",
    "I picked up some fresh fruit and a loaf of bread",
    "The cashier smiled and wished me a nice evening",
    "When I got home it started to rain softly",
    "I opened the window and listened to the sound of the rain",
    "Dinner was warm and comforting after a long day",
    "I cleaned the kitchen while humming a familiar tune",
    "Before bed I wrote a few lines in my journal",
    "I thought about how fast the week had gone by",
    "The moonlight filled my room through the open curtains",
    "I scrolled through social media for a few minutes before sleeping",
    "Dreams came and went without making much sense",
    "I woke up again to the sound of birds outside",
    "The smell of fresh coffee made me smile",
    "I decided to start my day with some stretching",
    "The floor felt cold beneath my feet as I moved around",
    "I checked the news but quickly got bored of it",
    "A friend called to share some exciting news",
    "I congratulated her and promised to meet soon",
    "Lunch today was leftovers from last night’s dinner",
    "I worked on a small project that had been pending for days",
    "The internet connection was slower than usual",
    "I made a playlist of songs I hadn’t heard in years",
    "The evening sky turned shades of orange and pink",
    "I took a few pictures to capture the moment",
    "Dinner was quick because I didn’t feel like cooking much",
    "I watched a short movie before going to bed",
    "My dreams were filled with strange but happy scenes",
    "The alarm went off but I hit snooze twice",
    "I finally got up when the room was already bright",
    "I checked my schedule for the day and sighed",
    "There were too many meetings but not enough motivation",
    "I brewed another cup of coffee and pushed myself to start",
    "The first meeting went better than I expected",
    "Someone made a joke that lightened the whole mood",
    "By afternoon I was craving a nap",
    "I stepped out for a walk to get some fresh air",
    "The air smelled of rain even though the sky was clear",
    "I met a dog that wagged its tail and followed me for a bit",
    "I smiled and wished the owner a good day",
    "When I got back I checked my phone again",
    "There was a message reminding me of an upcoming event",
    "I almost forgot that tomorrow was the weekend",
    "The thought of sleeping in made me happy",
    "Dinner was pasta with a bit too much cheese",
    "I didn’t mind because it still tasted amazing",
    "I sat by the window watching cars pass by",
    "The streetlights reflected softly on the wet road",
    "A song played in the background that reminded me of school days",
    "I thought about how much life had changed since then",
    "The clock struck eleven and I decided to call it a day",
    "Morning came with the sound of thunder in the distance",
    "The rain poured down but it felt oddly peaceful",
    "I made pancakes and watched a movie while eating",
    "The smell of vanilla filled the room",
    "After breakfast I cleaned my workspace and organized my notes",
    "I found an old sketchbook full of random doodles",
    "It made me want to start drawing again",
    "I spent the afternoon trying to sketch something simple",
    "The result wasn’t great but it made me feel calm",
    "Later I made a cup of hot chocolate and sat on the balcony",
    "The city looked quiet under the evening clouds",
    "I sent a few texts to friends asking how they were doing",
    "We planned to meet next week if everyone was free",
    "I cooked dinner while listening to a podcast about travel",
    "The host talked about exploring small towns and hidden trails",
    "I imagined walking through those peaceful streets someday",
    "The night was cool and perfect for a short stroll",
    "I locked the door and went out for a ten minute walk",
    "The neighborhood dogs barked as I passed by",
    "I waved at a kid riding his bicycle in circles",
    "Back home I poured myself a glass of water and sat quietly",
    "I scrolled through my photos and smiled at old memories",
    "The smell of rain still lingered in the air",
    "I turned off the lights and watched the ceiling fan spin",
    "It felt good to end the day without rushing anything",
    "Sleep came slowly but peacefully this time",
    "Morning light touched the walls and woke me up gently",
    "I stretched and took a deep breath before getting out of bed",
    "The world outside felt calm and full of promise",
    "I made my coffee and thought about what to do next",
    "Maybe today would bring something unexpected and nice"
]


In [100]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [101]:
tokenizer=Tokenizer()

In [102]:
tokenizer.fit_on_texts(dataset)


In [103]:
tokenizer.word_index

{'the': 1,
 'i': 2,
 'a': 3,
 'and': 4,
 'of': 5,
 'to': 6,
 'was': 7,
 'my': 8,
 'made': 9,
 'me': 10,
 'in': 11,
 'for': 12,
 'but': 13,
 'it': 14,
 'day': 15,
 'before': 16,
 'with': 17,
 'up': 18,
 'through': 19,
 'on': 20,
 'some': 21,
 'got': 22,
 'went': 23,
 'rain': 24,
 'dinner': 25,
 'about': 26,
 'by': 27,
 'that': 28,
 'cup': 29,
 'coffee': 30,
 'morning': 31,
 'than': 32,
 'today': 33,
 'watched': 34,
 'checked': 35,
 'sat': 36,
 'out': 37,
 'few': 38,
 'thought': 39,
 'much': 40,
 'felt': 41,
 'woke': 42,
 'myself': 43,
 'took': 44,
 'short': 45,
 'walk': 46,
 'an': 47,
 'old': 48,
 'usual': 49,
 'there': 50,
 'outside': 51,
 'window': 52,
 'turned': 53,
 'feel': 54,
 'too': 55,
 'lunch': 56,
 'after': 57,
 'fresh': 58,
 'smiled': 59,
 'evening': 60,
 'when': 61,
 'sound': 62,
 'while': 63,
 'bed': 64,
 'how': 65,
 'had': 66,
 'filled': 67,
 'room': 68,
 'came': 69,
 'again': 70,
 'smell': 71,
 'start': 72,
 'were': 73,
 'air': 74,
 'curtains': 75,
 'this': 76,
 'phone': 

In [104]:
# Making the input-output dataset for next-word prediction
# For example, given a tokenized sequence: [56, 7, 85, 13, 147, 148]
# We create multiple input-output pairs like this:
# Input | Output
# [56] | 7
# [56, 7] | 85
# [56, 7, 85] | 13
# [56, 7, 85, 13] | 147
# [56, 7, 85, 13, 147] | 148
# Each input sequence helps the LSTM learn to predict the next word in the sequence.


In [105]:
input_sequences=[]
'''[sentence] ensures the tokenizer sees it as a single text.

[0] extracts the actual sequence from the returned list.'''
for sentence in dataset:
    tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0] # converts sentences into vectors

    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])
    

In [106]:
input_sequences

[[2, 42],
 [2, 42, 18],
 [2, 42, 18, 125],
 [2, 42, 18, 125, 4],
 [2, 42, 18, 125, 4, 9],
 [2, 42, 18, 125, 4, 9, 43],
 [2, 42, 18, 125, 4, 9, 43, 3],
 [2, 42, 18, 125, 4, 9, 43, 3, 29],
 [2, 42, 18, 125, 4, 9, 43, 3, 29, 5],
 [2, 42, 18, 125, 4, 9, 43, 3, 29, 5, 30],
 [1, 126],
 [1, 126, 7],
 [1, 126, 7, 127],
 [1, 126, 7, 127, 19],
 [1, 126, 7, 127, 19, 1],
 [1, 126, 7, 127, 19, 1, 75],
 [1, 126, 7, 127, 19, 1, 75, 76],
 [1, 126, 7, 127, 19, 1, 75, 76, 31],
 [2, 44],
 [2, 44, 3],
 [2, 44, 3, 45],
 [2, 44, 3, 45, 46],
 [2, 44, 3, 45, 46, 16],
 [2, 44, 3, 45, 46, 16, 128],
 [2, 44, 3, 45, 46, 16, 128, 8],
 [2, 44, 3, 45, 46, 16, 128, 8, 129],
 [8, 77],
 [8, 77, 130],
 [8, 77, 130, 17],
 [8, 77, 130, 17, 3],
 [8, 77, 130, 17, 3, 78],
 [8, 77, 130, 17, 3, 78, 79],
 [8, 77, 130, 17, 3, 78, 79, 47],
 [8, 77, 130, 17, 3, 78, 79, 47, 48],
 [8, 77, 130, 17, 3, 78, 79, 47, 48, 80],
 [81, 82],
 [81, 82, 83],
 [81, 82, 83, 32],
 [81, 82, 83, 32, 49],
 [81, 82, 83, 32, 49, 33],
 [2, 131],
 [2, 13

In [107]:
# zero padding to make sure lists are of the same size

In [108]:
# Find the length of the longest sequence in input_sequences
# [len(x) for x in input_sequences] creates a list of lengths of all sequences
# max(...) then returns the maximum length among them
# This is useful for padding all sequences to the same length before feeding into the LSTM
max_length=max([len(x) for x in input_sequences]) 

In [109]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_length,padding='pre')

padded_input_sequences

array([[  0,   0,   0, ...,   0,   2,  42],
       [  0,   0,   0, ...,   2,  42,  18],
       [  0,   0,   0, ...,  42,  18, 125],
       ...,
       [  0,   0,   0, ..., 410, 121, 411],
       [  0,   0,   0, ..., 121, 411,   4],
       [  0,   0,   0, ..., 411,   4,  92]])

In [110]:
# input
X=padded_input_sequences[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0,   2],
       [  0,   0,   0, ...,   0,   2,  42],
       [  0,   0,   0, ...,   2,  42,  18],
       ...,
       [  0,   0,   0, ..., 409, 410, 121],
       [  0,   0,   0, ..., 410, 121, 411],
       [  0,   0,   0, ..., 121, 411,   4]])

In [111]:
# output
y=padded_input_sequences[:,-1]
y

array([ 42,  18, 125,   4,   9,  43,   3,  29,   5,  30, 126,   7, 127,
        19,   1,  75,  76,  31,  44,   3,  45,  46,  16, 128,   8, 129,
        77, 130,  17,   3,  78,  79,  47,  48,  80,  82,  83,  32,  49,
        33, 131,   1, 132,   4,  34,   1, 133, 134,  11,   1,  84,   7,
         3, 135, 136,  51,   8,  52,  53,  20,  21, 137,   6, 138,   1,
        31,  54, 139, 140, 141,  20,   1, 142, 143,  12, 144,  35,   8,
       145,  16,   1,  15,  22,  55, 146,   7,  85,  13, 147, 148, 149,
         3, 150, 151,   2,  86, 152,  87,  88,  56,   2,  36,  89,  17,
         3,  29,   5, 153,   4,   3, 154, 155, 156,  10,  11, 157,   2,
       158, 159,   5,  90,  23,  37,   6, 160, 161,   4, 162, 163,   3,
       164, 165,   7, 166,  32,  49,  33, 167,  18,  21,  58, 168,   4,
         3, 169,   5, 170, 171,  59,   4,  91,  10,   3,  92,  60,   2,
        22,  93,  14, 172,   6,  24,  94, 173,   1,  52,   4, 174,   6,
         1,  62,   5,   1,  24,   7, 175,   4, 176,  57,   3, 17

In [112]:
# Till this point we've converted a text-generation task into a supervised machine learning task, this is a multiclass-classification task as, the output is discrete 

In [113]:
X.shape

(832, 13)

In [114]:
y.shape

(832,)

In [115]:
len(tokenizer.word_index)

411

In [116]:
# one hot encoding the output (y)

from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=412) # num_classes = number of unique words in the vocabulary, we wrote 412 instead of 411 as tokenizer.word_index states from 1 and one hot encoding starts from 0 

In [117]:
y.shape

(832, 412)

In [118]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [119]:
# model
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [120]:
model=Sequential()
model.add(Embedding(412,100,input_shape=(14,)))
model.add(LSTM(250)) # number of nodes in each gate
model.add(Dense(412,activation='softmax')) # output layer 

In [121]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [122]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 14, 100)        │        41,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 250)            │       351,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 412)            │       103,412 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 495,612 (1.89 MB)

 Trainable params: 495,612 (1.89 MB)

 Non-trainable params: 0 (0.00 B)

In [123]:
history=model.fit(X,y,epochs=100)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.0270 - loss: 5.9642
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0464 - loss: 5.5474
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0481 - loss: 5.4878
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0444 - loss: 5.4661
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0526 - loss: 5.3871
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0501 - loss: 5.3120
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0545 - loss: 5.1690
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0566 - loss: 4.9355
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0848 - loss: 4.8319
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0987 - loss: 4.6385
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1251 - loss: 4.3818
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

In [124]:
# prediction 
text="friend"

# tokenize
tokenized=tokenizer.texts_to_sequences([text])[0]
# pad
padded=pad_sequences([tokenized],maxlen=14,padding='pre')
# predict
model.predict(padded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step


array([[6.30236116e-07, 1.94781114e-05, 2.87418770e-05, 6.10568037e-04,
        1.10330766e-05, 3.01280238e-06, 2.87192757e-03, 7.18062336e-04,
        1.26961662e-04, 3.99853662e-02, 1.67768088e-03, 1.47898379e-06,
        9.12298929e-05, 4.39270843e-06, 3.87156506e-05, 3.00085071e-06,
        4.74098761e-06, 5.41814115e-05, 1.15027389e-04, 2.63093767e-04,
        8.62366142e-05, 5.35195431e-05, 3.11005657e-04, 1.45082397e-03,
        3.07388778e-04, 3.32047464e-04, 7.11660177e-05, 2.07065095e-04,
        6.26411065e-06, 1.44627556e-04, 3.01905402e-05, 9.28842042e-07,
        2.28660909e-04, 3.99072887e-03, 5.93900797e-04, 6.95549184e-04,
        1.84966205e-03, 1.62880030e-03, 6.70563750e-05, 2.24015536e-03,
        1.09271268e-05, 1.74064673e-02, 2.68578087e-03, 7.63345161e-04,
        3.71029601e-03, 1.61951630e-05, 1.53940389e-04, 1.76905043e-04,
        3.98029661e-05, 9.43179548e-05, 4.07851246e-07, 1.12128990e-04,
        8.16466354e-07, 2.49532494e-03, 9.23735352e-05, 1.364282

In [129]:
import numpy as np
np.argmax(model.predict(padded))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


345

In [130]:
tokenizer.index_word[345]

'planned'

In [134]:
text='friend'

for i in range(5):
    token_text=tokenizer.texts_to_sequences([text])[0]
    padded=pad_sequences([token_text],maxlen=14,padding='pre')

    probabilities=model.predict(padded, verbose=0)

    most_probable_word=np.argmax(probabilities)

    next_word=tokenizer.index_word[most_probable_word]

    text=text + ' ' + next_word
    print(text)    



friend planned
friend planned to
friend planned to meet
friend planned to meet next
friend planned to meet next week


In [ ]:
# NOTE ON num_classes (+1 in to_categorical)
# ------------------------------------------------------------
# The core idea:
# The padding index 0 is implicit in the Tokenizer — it exists but is not visible
# in tokenizer.word_index. Tokenizer starts assigning indices from 1 onward.
#
# In one-hot encoding, we leave the 0th index for padding and start normally
# from the first index (1). But since we have to leave one position for
# the 0-padding or 0th index, we need to add one extra index position.
#
# So, if tokenizer.word_index gives 411 unique words (indices 1–411),
# we actually have 412 possible indices (0–411).
#
# Therefore:
#     num_classes = vocab_size + 1   # 411 + 1 = 412
#     y = to_categorical(y, num_classes=412)